skovgaard=function(model1,model2){
  X=model1$mu.x
  Z=model1$sigma.x
  X2=model2$mu.x
  Z2=model2$sigma.x
  n=nrow(X)
  mu=fitted(model1)
  mu2=fitted(model2)
  phi=model1$sigma.fv
  phi2=model2$sigma.fv
  labelsx1=colnames(X)
  labelsz1=colnames(Z)
  labelsx2=colnames(X2)
  labelsz2=colnames(Z2)
  p=ncol(X)+ncol(Z)
  q=p-(ncol(X2)+ncol(Z2))
  mu.link=model1$mu.link
  phi.link=model1$sigma.link
  d=function(m,mu,phi){
    (psigamma(mu*(1+phi)+phi+2,m-1)-
              psigamma(mu*(1+phi),m-1))
  }
  f=function(m,mu,phi){
    psigamma(mu*(1+phi)+phi+2,m-1)
  }
  j=function(k,m,mu,phi){
    (1+mu)^k*psigamma(mu*(1+phi)+phi+2,m-1)-
      mu^k*psigamma(mu*(1+phi),m-1)-
      psigamma(phi+2,m-1)
  }
  if(mu.link=="identity"){
    a1=1;a12=1;a2<-a22<-0
  }
  if(phi.link=="identity"){
    b1=1;b12=1;b2<-b22<-0
  }
  if(mu.link=="log"){
    a1<-a2<-mu;a12<-a22<-mu2
  }
  if(phi.link=="log"){
    b1<-b2<-phi;b12<-b22<-phi2
  }
  if(mu.link=="inverse"){
    a1=-mu^2;a12=-mu2^2;a2=mu^3;a22=mu2^3
  }
  if(phi.link=="inverse"){
    b1=-phi^2;b12=-phi2^2;b2=phi^3;b22=phi2^3
  }
  if(mu.link=="sqrt"){
    a1=2*X%*%model1$mu.coef;a12=2*X2%*%model2$mu.coef;
    a2<-a22<-2
  }
  if(phi.link=="sqrt"){
    b1=2*Z%*%model1$sigma.coef;b12=2*Z2%*%model2$sigma.coef;b2<-b22=2
  }
  D1hat=diag(c(a1),n)
  D1tilde=diag(c(a12),n)
  D2hat=diag(c(b1),n)
  D2tilde=diag(c(b12),n)
  PHIhat=diag(1+phi,n)
  PHItilde=diag(1+phi2,n)
  varya=-diag(d(2,mu,phi),n)
  varye=-diag(j(2,2,mu,phi),n)
  covyaye=-diag(mu*d(2,mu,phi)+f(2,mu,phi),n)
  y=model1$y
  ya=log(y/(1+y))
  ye=log(y^mu/(1+y)^(mu+1))
  muya=-d(1,mu,phi)
  muye=-j(1,1,mu,phi)
  E3hat=PHIhat^2*varya*D1hat^2
  E3tilde=-PHItilde^2*diag(d(2,mu2,phi2),n)*D1tilde^2
  E4hat=varye*D2hat^2
  E4tilde=-diag(j(2,2,mu2,phi2),n)*D2tilde^2
  E5hat=PHIhat*covyaye*D1hat*D2hat
  E5tilde=-PHItilde*diag(mu2*d(2,mu2,phi2)+f(2,mu2,phi2),n)*
    D1tilde*D2tilde
  D3hat=-E3hat+diag(c(a2),n)%*%PHIhat%*%diag(ya-muya,n)
  D3tilde=-E3tilde+diag(c(a22),n)%*%PHItilde%*%diag(ya-(
    -d(1,mu2,phi2)),n)
  D4hat=-E4hat+diag(c(b2),n)*diag(ye-muye,n)
  D4tilde=-E4tilde+diag(c(b22),n)*diag(log(y^mu2/(1+y)^(mu2+1))-(
    -j(1,1,mu2,phi2)
  ),n)
  D5hat=-E5hat+diag(ya-muya,n)*D1hat*D2hat
  D5tilde=-E5tilde+diag(ya-(
    -d(1,mu2,phi2)),
    n)*D1tilde*D2tilde
  Khat=rbind(cbind(t(X)%*%E3hat%*%X,t(X)%*%E5hat%*%Z),cbind(t(Z)%*%E5hat%*%X,t(Z)%*%E4hat%*%Z))
  Ktilde=rbind(cbind(t(X)%*%E3tilde%*%X,t(X)%*%E5tilde%*%Z),cbind(t(Z)%*%E5tilde%*%X,t(Z)%*%E4tilde%*%Z))
  K_1hat=solve(Khat)
  K_1tilde=solve(Ktilde)
  Jhat=rbind(cbind(t(X)%*%D3hat%*%X,t(X)%*%D5hat%*%Z),cbind(t(Z)%*%D5hat%*%X,t(Z)%*%D4hat%*%Z))
  Jtilde=rbind(cbind(t(X)%*%D3tilde%*%X,t(X)%*%D5tilde%*%Z),cbind(t(Z)%*%D5tilde%*%X,t(Z)%*%D4tilde%*%Z))
  J11=as.matrix(
    Jtilde[!c(labelsx1%in%labelsx2,labelsz1%in%labelsz2),
           !c(labelsx1%in%labelsx2,labelsz1%in%labelsz2)]
  )
  V1=varya
  MUhat=diag(mu,n)
  MUtilde=diag(mu2,n)
  C=-diag(f(2,mu,phi),n)
  V2=-diag(j(0,2,mu,phi))-V1+C
  UP1=t(X)%*%PHIhat%*%D1hat%*%V1%*%D1tilde%*%PHItilde%*%X
  UP2=t(X)%*%PHIhat%*%D1hat%*%(V1%*%MUtilde+C)%*%D2tilde%*%Z
  UP2t=t(Z)%*%D2hat%*%(V1%*%MUhat+C)%*%D1tilde%*%PHItilde%*%X
  UP3=t(Z)%*%D2hat%*%(V1%*%MUhat%*%MUtilde+C%*%(MUhat+MUtilde)+V2)%*%
    D2tilde%*%Z
  UP=rbind(cbind(UP1,UP2),cbind(UP2t,UP3))
  Utilde=c(t(X)%*%PHItilde%*%D1tilde%*%(ya-(
    -d(1,mu2,phi2))),
           t(Z)%*%D2tilde%*%(log(y^mu2/(1+y)^(mu2+1))-(
             -j(1,1,mu2,phi2)
           )))
  up=c(t(X)%*%PHIhat%*%D1hat%*%(V1%*%(MUhat%*%PHIhat-MUtilde%*%PHItilde)+C%*%(PHIhat-PHItilde))%*%rep(1,n),
       t(Z)%*%D2hat%*%((V1%*%MUhat+C)%*%(MUhat%*%PHIhat-MUtilde%*%PHItilde)+(C%*%MUhat+V2-C)%*%(PHIhat-PHItilde))%*%rep(1,n))
  LR=abs(model1$G.dev-model2$G.dev)
  epsa=sqrt(abs(det(Ktilde)*det(Khat)*det(J11)))
  epsb=(abs(det(UP))*sqrt(abs(det(as.matrix((Ktilde%*%solve(UP)%*%Jhat%*%K_1hat%*%UP)[!c(labelsx1%in%labelsx2,labelsz1%in%labelsz2),!c(labelsx1%in%labelsx2,labelsz1%in%labelsz2)])))))
  epsc=abs(t(Utilde)%*%solve(UP)%*%Khat%*%solve(Jhat)%*%UP%*%K_1tilde%*%Utilde)^(q/2)
  epsd=abs(LR^(q/2-1)%*%t(Utilde)%*%solve(UP)%*%up)
  eps=epsa/epsb*epsc/epsd
  return(eps)
}
